server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: nghiameow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 601898567894-qbuf87vdar20sifb9p0bpatdq9j5haqq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8081/login/oauth2/code/google

jwt:
  secret: +l1svovoRY7LBy+jNvD/Rv+K1o+4kriJBtYH0W/xYCqEaRq12I+BAStZvg/YKoEF
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
